{
 "title": "Monitoring PostgreSQL Server, Postgres replication",
 "description": "Dashboard que coleta as seguintes informações:\r\nOS: Linux \r\nMétrics: CPU, Memória, Disco, Swap, Processos, Load Averages, PostgreSQL, Postgres Replication",
 "tags": [
  "PostgreSQL",
  "Linux"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage %",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "CPU Usage %",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_idle\") * -1 + 100 AS \"mean_usage_idle\" FROM \"cpu\" WHERE time > now() - 30m AND \"cpu\"='cpu-total' GROUP BY time(30s) FILL(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pgsql-box-A" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Server Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "format": "h",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Bom Uptime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"uptime_format\") AS \"last_uptime_format\" FROM \"system\" WHERE time > now() - 30m ",
     "select": [
      [
       { "params": [ "uptime_format" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "postgres01" }
     ]
    }
   ]
  },
  {
   "title": "User Connections",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(1) from pg_stat_activity where usename != 'telegraf';"
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"free\") AS \"mean_free\" FROM \"disk\" WHERE time > now() - 1h AND \"path\"='/' GROUP BY time(30s) FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Used %",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "Memory Used %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"used_percent\") AS \"mean_used_percent\" FROM \"mem\" WHERE time > now() - 30m GROUP BY time(30s) FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL Activities",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "select  \nusename as \"User\", \napplication_name as \"App\", \nclient_addr as \"IP\", \nto_char(backend_start, 'YYYY-MM-DD HH24:MI:SS') as \"TimeConnect\", \nto_char(query_start, 'YYYY-MM-DD HH24:MI:SS') as \"TimeQuery\", \nto_char(state_change, 'YYYY-MM-DD HH24:MI:SS') as \"TimeState\", \nstate,\nquery as \"Query\"\nfrom pg_stat_activity \nwhere pid <> pg_backend_pid() \nand usename != 'telegraf'\norder by backend_start;"
    }
   ]
  },
  {
   "title": "Replication detail from Slave",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "select case when pg_is_in_recovery() is true then 'in recovery' else 'not recovery' end as is_in_recovery, \npg_last_xlog_receive_location() as xlog_receive, \npg_last_xlog_replay_location() as xlog_replay;"
    }
   ]
  },
  {
   "title": "Replication detail from Master",
   "type": "table",
   "gridPos": { "h": 3, "w": 16, "x": 8, "y": 13 },
   "targets": [
    {
     "rawSql": "select   pid, client_addr, state, sync_state, pg_current_xlog_location(),\n         pg_xlog_location_diff(sent_location, write_location) as write_lag,  \n         pg_xlog_location_diff(sent_location, flush_location) as flush_lag,  \n         pg_xlog_location_diff(sent_location, replay_location) as replay_lag\nfrom pg_stat_replication ;"
    }
   ]
  },
  {
   "title": "Is in Recovery?",
   "type": "graph",
   "description": "1 = True\n0 = False",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Is in Recovery",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"is_in_recovery\") AS \"mean_is_in_recovery\" FROM \"pg_is_in_recovery\" WHERE time > now() - 30m GROUP BY time(30s) FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lag Replication in Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Write Lag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"write_lag\") AS \"mean_write_lag\" FROM \"pg_stat_replication\" WHERE time > now() - 30m GROUP BY time(10s) FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Flush Lag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"flush_lag\") AS \"mean_flush_lag\" FROM \"pg_stat_replication\" WHERE time > now() - 30m GROUP BY time(10s) FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Replay Lag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"replay_lag\") AS \"mean_replay_lag\" FROM \"pg_stat_replication\" WHERE time > now() - 30m GROUP BY time(10s) FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lag Replication in Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "xlog Delay",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"log_delay\") AS \"mean_log_delay\" FROM \"pg_log_delay\" WHERE time > now() - 30m GROUP BY time(10s) FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Quick View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true
  },
  {
   "title": "CPU/Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "usage_idle",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"usage_idle\") AS \"mean_usage_idle\" FROM \"cpu\" WHERE time > now() - 30m GROUP BY time(30s) FILL(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "usage_iowait",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"usage_iowait\") AS \"mean_usage_iowait\" FROM \"cpu\" WHERE time > now() - 30m GROUP BY time(30s) FILL(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "usage_user",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"usage_user\") AS \"mean_usage_user\" FROM \"cpu\" WHERE time > now() - 30m GROUP BY time(30s) FILL(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "usage_system",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"usage_system\") AS \"mean_usage_system\" FROM \"cpu\" WHERE time > now() - 30m GROUP BY time(30s) FILL(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select \"blocked\",\"running\",\"sleeping\",\"total\",\"total_threads\",\"zombies\" from \"processes\" where $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Load Averages",
     "type": "graph",
     "description": "Cada métrica significa o tempo, 1, 5, 15 minutos respectivamente. Esses são os valores médios dos processos esperando execução.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "1 Minuto",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"load1\") FROM \"system\" WHERE $timeFilter GROUP BY time(30s) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "5 Minutos",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"load5\") FROM \"system\" WHERE $timeFilter GROUP BY time(30s) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "15 Minutos",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"load15\") FROM \"system\" WHERE $timeFilter GROUP BY time(30s) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory/Swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "total",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "used",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "available",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "query": "SELECT mean(\"available\") FROM \"mem\" WHERE (\"host\" = 'postgres01') AND $timeFilter GROUP BY time(30s) fill(null)",
       "select": [
        [
         { "params": [ "available" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Memory Distribution",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "free",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "buffered",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "buffered" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "cached",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "cached" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Swap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"total\") AS \"total\", mean(\"used\") AS \"used\", mean(\"free\") AS \"free\" FROM \"swap\" WHERE time > now() - 30m GROUP BY time(30s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Swap Activity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"in\") AS \"in\", mean(\"out\") AS \"out\" FROM \"swap\" WHERE time > now() - 30m GROUP BY time(30s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"total\") AS \"total\" FROM \"disk\" WHERE time > now() - 30m AND \"path\"='/' GROUP BY time(30s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"free\") AS \"free\" FROM \"disk\" WHERE time > now() - 30m AND \"path\"='/' GROUP BY time(30s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"used\") AS \"used\" FROM \"disk\" WHERE time > now() - 30m AND \"path\"='/' GROUP BY time(30s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk I/O Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(\"read_bytes\"), 30s) AS \"read_bytes\", non_negative_derivative(mean(\"write_bytes\"), 30s) AS \"write_bytes\" FROM \"diskio\" WHERE time > now() - 30m GROUP BY time(30s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection Status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "total",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"amount\") AS \"total connections\" FROM \"pg_connections\" WHERE time > now() - 30m GROUP BY time(30s) FILL(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_state",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"amount\") AS \"mean_amount\" FROM \"pg_connections\" WHERE time > now() - 30m GROUP BY time(30s), \"state\" FILL(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Tuples Out",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(\"tup_fetched\"),30s) AS \"fetched\", non_negative_derivative(mean(\"tup_returned\"),30s) AS \"returned\" FROM \"postgresql\" WHERE time > now() - 30m AND \"db\"='postgres' GROUP BY time(30s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Tuples In",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(\"tup_inserted\"),30s) AS \"inserts\", non_negative_derivative(mean(\"tup_updated\"),30s) AS \"updates\", non_negative_derivative(mean(\"tup_deleted\"),10s) AS \"deletes\" FROM \"postgresql\" WHERE time > now() - 30m AND \"db\"='postgres' GROUP BY time(30s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Conflicts/Deadlocks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "conflicts",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "conflicts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ]
      },
      {
       "alias": "deadlocks",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "deadlocks" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Buffers Allocated",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "buffers_alloc" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ]
      },
      {
       "alias": "Buffers Backend",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "buffers_backend" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ]
      },
      {
       "alias": "Buffers Backend Fsync",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "buffers_backend_fsync" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ]
      },
      {
       "alias": "Buffers Checkpoint",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "buffers_checkpoint" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "postgres01" }
       ]
      },
      {
       "alias": "Buffers Clean",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "buffers_clean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "PostgreSQL Schemas Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_schema_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(\"size_mb\") AS \"mean_size_mb\" FROM \"pg_schemas_size\" WHERE time > now() - 30m GROUP BY time(30s), \"schema_name\" FILL(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true
  },
  {
   "title": "Postgresql Activities",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true
  }
 ]
}