---

version: "3.1"

networks:
  app-tier:
    driver: bridge

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    restart: always
    expose:
      - '3000'
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./config/provisioning/:/etc/grafana/provisioning/
    environment:
      - 'TZ=${TIMEZONE}'
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel
    depends_on:
      - influxdb
    networks:
      - app-tier

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    hostname: influxdb
    restart: always
    volumes:
      - ./config/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./data/influxdb:/var/lib/influxdb:rw
    environment:
      - 'TZ=${TIMEZONE}'
      - INFLUXDB_DB=${INFLUXDB_DATABASE}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    expose:
      - '8086'
    depends_on:
      - telegraf
    networks:
      - app-tier

  telegraf:
    image: telegraf:1.12.5-alpine
    container_name: telegraf
    hostname: telegraf
    restart: always
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - 'TZ=${TIMEZONE}'
    expose:
      - '8094'
    networks:
      - app-tier

  httpd:
    container_name: nginx
    image: bitnami/nginx:${NGINX_VERSION}-${OS_VERSION}
    hostname: nginx
    restart: always
    environment:
      - 'TZ=${TIMEZONE}'
    networks:
      - app-tier
    ports:
      - '80:8080'
      - '443:443'
    volumes:
      - ./config/nginx/vhost:/opt/bitnami/nginx/conf/vhosts:ro
      - ./logs/nginx:/opt/bitnami/nginx/logs:rw
